// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClVbOLKVHS1ZQkxL8L-1_1DkqF4ql2xZw',
    appId: '1:844023932526:web:94a52773651423ffe6287f',
    messagingSenderId: '844023932526',
    projectId: 'y2-copilot',
    authDomain: 'y2-copilot.firebaseapp.com',
    storageBucket: 'y2-copilot.firebasestorage.app',
    measurementId: 'G-07FQ4F466S',
  );

  // TODO: Replace with your actual Firebase configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQWrpwg4-XcOaBDzXGJ6qCkm3LWy6MwFM',
    appId: '1:844023932526:android:10a1f9efc905da9ce6287f',
    messagingSenderId: '844023932526',
    projectId: 'y2-copilot',
    storageBucket: 'y2-copilot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzui80TWC0OqTMuLVFANLF8oGdUOM_600',
    appId: '1:844023932526:ios:ebae2ae78961ff19e6287f',
    messagingSenderId: '844023932526',
    projectId: 'y2-copilot',
    storageBucket: 'y2-copilot.firebasestorage.app',
    iosClientId: '844023932526-fh40gdk1fobo6eusbv1rvbendh7ohm0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzui80TWC0OqTMuLVFANLF8oGdUOM_600',
    appId: '1:844023932526:ios:ebae2ae78961ff19e6287f',
    messagingSenderId: '844023932526',
    projectId: 'y2-copilot',
    storageBucket: 'y2-copilot.firebasestorage.app',
    iosClientId: '844023932526-fh40gdk1fobo6eusbv1rvbendh7ohm0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClVbOLKVHS1ZQkxL8L-1_1DkqF4ql2xZw',
    appId: '1:844023932526:web:115fb6c410d7c9ebe6287f',
    messagingSenderId: '844023932526',
    projectId: 'y2-copilot',
    authDomain: 'y2-copilot.firebaseapp.com',
    storageBucket: 'y2-copilot.firebasestorage.app',
    measurementId: 'G-EPT0Q2YETN',
  );

}