import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          OnboardingScreen(),
        ]),
      ),
    );
  }
}

class OnboardingScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 13,
                top: 37,
                child: Container(
                  width: 364,
                  height: 43,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
                  ),
                ),
              ),
              Positioned(
                left: 55,
                top: 59,
                child: SizedBox(
                  width: 283,
                  height: 59,
                  child: Text(
                    'WELCOME TO Y^2',
                    style: TextStyle(
                      color: const Color(0xFF2A2727),
                      fontSize: 38.02,
                      fontFamily: 'That That New Pixel Test',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: -43,
                child: Opacity(
                  opacity: 0.28,
                  child: Text(
                    'Y',
                    style: TextStyle(
                      color: Colors.black.withValues(alpha: 0.13),
                      fontSize: 700,
                      fontFamily: 'Belmonte Ballpoint Trial',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 141,
                top: 764,
                child: Opacity(
                  opacity: 0.70,
                  child: Text(
                    'SIGN UP/ LOG IN',
                    style: TextStyle(
                      color: const Color(0xFF646262),
                      fontSize: 21.41,
                      fontFamily: 'PP NeueBit',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
