import sqlglot
from sqlglot import exp
import sqlite3
import json
from typing import Dict, List, Tuple

def get_dynamic_schema(db_path: str) -> Dict[str, List[str]]:
    """
    Introspects the SQLite database to get the actual schema dynamically.
    This function is the single source of truth for your database structure.
    """
    schema = {}
    try:
        with sqlite3.connect(db_path) as conn:
            cursor = conn.cursor()
            # Get all table names
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
            tables = [table[0] for table in cursor.fetchall()]
            # Get columns for each table
            for table in tables:
                cursor.execute(f"PRAGMA table_info('{table}')")
                columns = [info[1] for info in cursor.fetchall()]
                schema[table] = columns
    except sqlite3.Error as e:
        print(f"Database error: {e}")
        return {} # Return empty schema on error
    return schema

def validate_sql_query(generated_sql: str, db_path: str) -> Tuple[bool, str]:
    """
    Validates a generated SQL query against the live database schema using sqlglot.
    This is the programmatic guardrail that prevents hallucinated SQL from running.

    Args:
        generated_sql: The SQL query generated by the LLM.
        db_path: The path to the SQLite database file.

    Returns:
        A tuple of (is_valid: bool, reason: str).
    """
    # 1. Get the ground-truth schema directly from the database
    actual_schema = get_dynamic_schema(db_path)
    if not actual_schema:
        return False, "Validation Error: Could not load database schema."

    actual_tables = {table.lower() for table in actual_schema.keys()}
    all_actual_columns = {col.lower() for cols in actual_schema.values() for col in cols}

    try:
        # 2. Parse the SQL. If it's not valid SQL, this will fail.
        parsed = sqlglot.parse_one(generated_sql, read="sqlite")

        # 3. Enforce read-only: Only allow SELECT statements.
        if not isinstance(parsed, exp.Select):
            return False, "Security Error: Only SELECT statements are permitted."

        # 4. Validate every table mentioned in the query
        query_tables = {table.name.lower() for table in parsed.find_all(exp.Table)}
        for table in query_tables:
            if table not in actual_tables:
                return False, f"Schema Error: Table '{table}' does not exist in the database. Available tables are: {', '.join(sorted(actual_tables))}"

        # 5. Validate every column mentioned in the query
        query_columns = {col.name.lower() for col in parsed.find_all(exp.Column)}
        # Ignore wildcard columns for this check
        query_columns.discard('*')
        for column in query_columns:
            if column not in all_actual_columns:
                return False, f"Schema Error: Column '{column}' does not exist in the database."

    except sqlglot.errors.ParseError as e:
        return False, f"Syntax Error: The generated SQL is not valid. Details: {e}"
    except Exception as e:
        # Broad exception to catch any other potential issues.
        return False, f"Validation Error: An unexpected error occurred while validating the SQL. Details: {e}"

    return True, "Query is valid."
